{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nodechecker.fullname" . }}
  labels:
{{ include "nodechecker.labels" . | indent 4 }}
rules:
- apiGroups:
    - "*"
  resources:
    - "events"
  verbs:
    - "create"
- apiGroups:
    - "*"
  resources:
    - "nodecheckers"
    - "nodes"
    - "events"
    - "endpoints"
  verbs:
    - "get"
    - "watch"
    - "list"
    - "update"
    - "patch"
    - "create"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nodechecker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "nodechecker.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "nodechecker.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nodechecker.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}    
{{- end -}}