{{- if and .Values.service.enable -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodechecker.fullname" . }}
  labels:
{{ include "nodechecker.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
{{ include "nodechecker.labels" . | indent 4 }}
{{- if .Values.service.ports }}
  ports:
{{ toYaml .Values.service.ports | indent 4 }}
{{- end -}}
{{- end}}
