// +build !ignore_autogenerated

/*
Copyright 2022

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionCheck) DeepCopyInto(out *ConnectionCheck) {
	*out = *in
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = make([]TargetExternal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClusterNodes != nil {
		in, out := &in.ClusterNodes, &out.ClusterNodes
		*out = make([]TargetClusterNodes, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClusterEndpoints != nil {
		in, out := &in.ClusterEndpoints, &out.ClusterEndpoints
		*out = make([]TargetClusterEndpoints, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionCheck.
func (in *ConnectionCheck) DeepCopy() *ConnectionCheck {
	if in == nil {
		return nil
	}
	out := new(ConnectionCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureCheck) DeepCopyInto(out *FeatureCheck) {
	*out = *in
	if in.SyncLabels != nil {
		in, out := &in.SyncLabels, &out.SyncLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureCheck.
func (in *FeatureCheck) DeepCopy() *FeatureCheck {
	if in == nil {
		return nil
	}
	out := new(FeatureCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeChecker) DeepCopyInto(out *NodeChecker) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeChecker.
func (in *NodeChecker) DeepCopy() *NodeChecker {
	if in == nil {
		return nil
	}
	out := new(NodeChecker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeChecker) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeCheckerList) DeepCopyInto(out *NodeCheckerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeChecker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeCheckerList.
func (in *NodeCheckerList) DeepCopy() *NodeCheckerList {
	if in == nil {
		return nil
	}
	out := new(NodeCheckerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeCheckerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeCheckerSpec) DeepCopyInto(out *NodeCheckerSpec) {
	*out = *in
	in.SourceNodes.DeepCopyInto(&out.SourceNodes)
	in.ConnectionCheck.DeepCopyInto(&out.ConnectionCheck)
	in.FeatureCheck.DeepCopyInto(&out.FeatureCheck)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeCheckerSpec.
func (in *NodeCheckerSpec) DeepCopy() *NodeCheckerSpec {
	if in == nil {
		return nil
	}
	out := new(NodeCheckerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeCheckerSpecSourceNodes) DeepCopyInto(out *NodeCheckerSpecSourceNodes) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeCheckerSpecSourceNodes.
func (in *NodeCheckerSpecSourceNodes) DeepCopy() *NodeCheckerSpecSourceNodes {
	if in == nil {
		return nil
	}
	out := new(NodeCheckerSpecSourceNodes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeCheckerStatus) DeepCopyInto(out *NodeCheckerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeCheckerStatus.
func (in *NodeCheckerStatus) DeepCopy() *NodeCheckerStatus {
	if in == nil {
		return nil
	}
	out := new(NodeCheckerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetClusterEndpoints) DeepCopyInto(out *TargetClusterEndpoints) {
	*out = *in
	in.Endpoint.DeepCopyInto(&out.Endpoint)
	if in.SyncLabels != nil {
		in, out := &in.SyncLabels, &out.SyncLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetClusterEndpoints.
func (in *TargetClusterEndpoints) DeepCopy() *TargetClusterEndpoints {
	if in == nil {
		return nil
	}
	out := new(TargetClusterEndpoints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetClusterEndpointsEndpoint) DeepCopyInto(out *TargetClusterEndpointsEndpoint) {
	*out = *in
	if in.SyncLabels != nil {
		in, out := &in.SyncLabels, &out.SyncLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetClusterEndpointsEndpoint.
func (in *TargetClusterEndpointsEndpoint) DeepCopy() *TargetClusterEndpointsEndpoint {
	if in == nil {
		return nil
	}
	out := new(TargetClusterEndpointsEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetClusterNodes) DeepCopyInto(out *TargetClusterNodes) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SyncLabels != nil {
		in, out := &in.SyncLabels, &out.SyncLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetClusterNodes.
func (in *TargetClusterNodes) DeepCopy() *TargetClusterNodes {
	if in == nil {
		return nil
	}
	out := new(TargetClusterNodes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetExternal) DeepCopyInto(out *TargetExternal) {
	*out = *in
	if in.SyncLabels != nil {
		in, out := &in.SyncLabels, &out.SyncLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetExternal.
func (in *TargetExternal) DeepCopy() *TargetExternal {
	if in == nil {
		return nil
	}
	out := new(TargetExternal)
	in.DeepCopyInto(out)
	return out
}
